// Code generated by authara-sdk-gen from authara-core/contract/openapi.yaml; DO NOT EDIT.

package authara

import (
	"context"
	"net/http"
	"net/url"
	"strconv"

	"github.com/google/uuid"
)

func apiRequestOptions(incoming *http.Request, cookies []string, csrf bool) []requestOption {
	var opts []requestOption
	if len(cookies) > 0 {
		opts = append(opts, func(req *http.Request) {
			if incoming == nil {
				return
			}
			for _, name := range cookies {
				if cookie, err := incoming.Cookie(name); err == nil {
					req.AddCookie(cookie)
				}
			}
		})
	}
	if csrf {
		if token, ok := CSRFToken(incoming); ok {
			opts = append(opts, withCSRFToken(token))
		}
	}
	return opts
}

func (c *Client) CallGetCurrentAccount(ctx context.Context, incoming *http.Request, sessionsCursor string, sessionsLimit int, passkeysCursor string, passkeysLimit int) (*APIAccount, error) {
	var out APIAccount
	path := "/auth/api/v1/account"
	query := url.Values{}
	query.Set("sessions_cursor", sessionsCursor)
	query.Set("sessions_limit", strconv.FormatInt(int64(sessionsLimit), 10))
	query.Set("passkeys_cursor", passkeysCursor)
	query.Set("passkeys_limit", strconv.FormatInt(int64(passkeysLimit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLinkCurrentUserApple(ctx context.Context, incoming *http.Request, body APIAppleAuthorizationRequest) error {
	path := "/auth/api/v1/account/auth-methods/apple"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_apple_oauth", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallLinkCurrentUserGoogle(ctx context.Context, incoming *http.Request, body APIGoogleLoginRequest) error {
	path := "/auth/api/v1/account/auth-methods/google"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallUnlinkCurrentUserAuthMethod(ctx context.Context, incoming *http.Request, provider string) error {
	path := "/auth/api/v1/account/auth-methods/" + url.PathEscape(provider) + ""
	_, err := c.doJSONBody(ctx, http.MethodDelete, path, nil, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallStartCurrentUserEmailChange(ctx context.Context, incoming *http.Request, body APIEmailChangeRequest) (*APIChallengeReference, error) {
	var out APIChallengeReference
	path := "/auth/api/v1/account/email-change/challenges"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallVerifyCurrentUserEmailChange(ctx context.Context, incoming *http.Request, body APIChallengeVerification) error {
	path := "/auth/api/v1/account/email-change/challenges/verify"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallDeleteCurrentUserPasskey(ctx context.Context, incoming *http.Request, passkeyID uuid.UUID) error {
	path := "/auth/api/v1/account/passkeys/" + url.PathEscape(passkeyID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodDelete, path, nil, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallAddCurrentUserPassword(ctx context.Context, incoming *http.Request, body APISetPasswordRequest) error {
	path := "/auth/api/v1/account/password"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallChangeCurrentUserPassword(ctx context.Context, incoming *http.Request, body APIChangePasswordRequest) error {
	path := "/auth/api/v1/account/password"
	_, err := c.doJSONBody(ctx, http.MethodPut, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallRevokeCurrentUserOtherSessions(ctx context.Context, incoming *http.Request) error {
	path := "/auth/api/v1/account/sessions/others"
	_, err := c.doJSONBody(ctx, http.MethodDelete, path, nil, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallRevokeCurrentUserSession(ctx context.Context, incoming *http.Request, sessionID uuid.UUID) error {
	path := "/auth/api/v1/account/sessions/" + url.PathEscape(sessionID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodDelete, path, nil, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallChangeCurrentUsername(ctx context.Context, incoming *http.Request, body APIChangeUsernameRequest) error {
	path := "/auth/api/v1/account/username"
	_, err := c.doJSONBody(ctx, http.MethodPatch, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallGetPublicCapabilities(ctx context.Context, incoming *http.Request) (*APICapabilities, error) {
	var out APICapabilities
	path := "/auth/api/v1/capabilities"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallResendChallenge(ctx context.Context, incoming *http.Request, body APIChallengeReference) error {
	path := "/auth/api/v1/challenges/resend"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallGetCSRFToken(ctx context.Context) (*APICSRFToken, error) {
	var out APICSRFToken
	path := "/auth/api/v1/csrf"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallAcceptInvitation(ctx context.Context, incoming *http.Request, audience string, body APIInvitationTokenRequest) (*APITokens, error) {
	var out APITokens
	path := "/auth/api/v1/invitations/accept"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallAuthenticateAndAcceptInvitationWithGoogle(ctx context.Context, incoming *http.Request, audience string, body APIInvitationGoogleRequest) (*APIInvitationGoogleResult, error) {
	var out APIInvitationGoogleResult
	path := "/auth/api/v1/invitations/google"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginAndAcceptInvitation(ctx context.Context, incoming *http.Request, audience string, body APIInvitationPasswordLoginRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/invitations/login"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallPreviewInvitation(ctx context.Context, token string) (*APIInvitationPreview, error) {
	var out APIInvitationPreview
	path := "/auth/api/v1/invitations/preview"
	query := url.Values{}
	query.Set("token", token)
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginWithPassword(ctx context.Context, incoming *http.Request, audience string, body APIPasswordLoginRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/login"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginWithApple(ctx context.Context, incoming *http.Request, audience string, body APIAppleAuthorizationRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/oauth/apple"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_apple_oauth", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetAppleLoginOptions(ctx context.Context) (*APIAppleLoginOptions, error) {
	var out APIAppleLoginOptions
	path := "/auth/api/v1/oauth/apple/options"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallLoginWithGoogle(ctx context.Context, incoming *http.Request, audience string, body APIGoogleLoginRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/oauth/google"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetGoogleLoginOptions(ctx context.Context) (*APIGoogleLoginOptions, error) {
	var out APIGoogleLoginOptions
	path := "/auth/api/v1/oauth/google/options"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListCurrentUserOrganizations(ctx context.Context, incoming *http.Request, cursor string, limit int) (*APIOrganizationSummaries, error) {
	var out APIOrganizationSummaries
	path := "/auth/api/v1/organizations"
	query := url.Values{}
	query.Set("cursor", cursor)
	query.Set("limit", strconv.FormatInt(int64(limit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetCurrentOrganization(ctx context.Context, incoming *http.Request) (*APIOrganizationSummary, error) {
	var out APIOrganizationSummary
	path := "/auth/api/v1/organizations/current"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListCurrentOrganizationMembers(ctx context.Context, incoming *http.Request, cursor string, limit int) (*APICurrentOrganizationMembers, error) {
	var out APICurrentOrganizationMembers
	path := "/auth/api/v1/organizations/current/members"
	query := url.Values{}
	query.Set("cursor", cursor)
	query.Set("limit", strconv.FormatInt(int64(limit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID) (*APIOrganizationEnvelope, error) {
	var out APIOrganizationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallUpdatePublicOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, body APIUpdateOrganizationRequest) (*APIOrganizationEnvelope, error) {
	var out APIOrganizationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodPatch, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListPublicOrganizationInvitations(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, cursor string, limit int) (*APIOrganizationInvitations, error) {
	var out APIOrganizationInvitations
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations"
	query := url.Values{}
	query.Set("cursor", cursor)
	query.Set("limit", strconv.FormatInt(int64(limit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganizationInvitation(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallRevokePublicOrganizationInvitation(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + "/revoke"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallListPublicOrganizationMembers(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, cursor string, limit int) (*APIOrganizationMembers, error) {
	var out APIOrganizationMembers
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members"
	query := url.Values{}
	query.Set("cursor", cursor)
	query.Set("limit", strconv.FormatInt(int64(limit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetPublicOrganizationMember(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, userID uuid.UUID) (*APIOrganizationMemberEnvelope, error) {
	var out APIOrganizationMemberEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members/" + url.PathEscape(userID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallUpdatePublicOrganizationMember(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, userID uuid.UUID, body APIUpdateOrganizationMemberRequest) (*APIOrganizationMemberEnvelope, error) {
	var out APIOrganizationMemberEnvelope
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members/" + url.PathEscape(userID.String()) + ""
	_, err := c.doJSONBody(ctx, http.MethodPatch, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSwitchOrganization(ctx context.Context, incoming *http.Request, organizationID uuid.UUID, audience string) (*APITokens, error) {
	var out APITokens
	path := "/auth/api/v1/organizations/" + url.PathEscape(organizationID.String()) + "/switch"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallFinishPasskeyAuthentication(ctx context.Context, incoming *http.Request, audience string, body APIPasskeyAuthenticationFinishRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/passkeys/authenticate/finish"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallBeginPasskeyAuthentication(ctx context.Context, incoming *http.Request) (*APIPasskeyOptions, error) {
	var out APIPasskeyOptions
	path := "/auth/api/v1/passkeys/authenticate/options"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallFinishPasskeyRegistration(ctx context.Context, incoming *http.Request, body APIPasskeyRegistrationFinishRequest) error {
	path := "/auth/api/v1/passkeys/register/finish"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallBeginPasskeyRegistration(ctx context.Context, incoming *http.Request) (*APIPasskeyOptions, error) {
	var out APIPasskeyOptions
	path := "/auth/api/v1/passkeys/register/options"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallStartPasswordResetChallenge(ctx context.Context, incoming *http.Request, body APIPasswordResetRequest) (*APIChallengeReference, error) {
	var out APIChallengeReference
	path := "/auth/api/v1/password-reset/challenges"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallVerifyPasswordResetChallenge(ctx context.Context, incoming *http.Request, body APIPasswordResetChallengeVerification) error {
	path := "/auth/api/v1/password-reset/challenges/verify"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallStartGoogleAccountRecoveryLink(ctx context.Context, incoming *http.Request, body APIGoogleLoginRequest) (*APIAccountRecoveryLink, error) {
	var out APIAccountRecoveryLink
	path := "/auth/api/v1/provider-links/recovery/google"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCompleteAccountRecoveryLinkWithApple(ctx context.Context, incoming *http.Request, linkID uuid.UUID, audience string, body APIAccountRecoveryAppleProofRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/provider-links/recovery/" + url.PathEscape(linkID.String()) + "/apple"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_apple_oauth", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCompleteAccountRecoveryLinkWithGoogle(ctx context.Context, incoming *http.Request, linkID uuid.UUID, audience string, body APIAccountRecoveryGoogleProofRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/provider-links/recovery/" + url.PathEscape(linkID.String()) + "/google"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCompleteAccountRecoveryLinkWithPassword(ctx context.Context, incoming *http.Request, linkID uuid.UUID, audience string, body APIAccountRecoveryPasswordProofRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/provider-links/recovery/" + url.PathEscape(linkID.String()) + "/password"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallReauthenticateWithApple(ctx context.Context, incoming *http.Request, body APIAppleReauthenticationRequest) error {
	path := "/auth/api/v1/reauthenticate/apple"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_apple_oauth", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallCheckRecentAuthentication(ctx context.Context, incoming *http.Request) error {
	path := "/auth/api/v1/reauthenticate/check"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallReauthenticateWithGoogle(ctx context.Context, incoming *http.Request, body APIGoogleReauthenticationRequest) error {
	path := "/auth/api/v1/reauthenticate/google"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf", "authara_oauth_nonce"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallFinishPasskeyReauthentication(ctx context.Context, incoming *http.Request, body APIPasskeyReauthenticationFinishRequest) error {
	path := "/auth/api/v1/reauthenticate/passkeys/finish"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallBeginPasskeyReauthentication(ctx context.Context, incoming *http.Request, body APIAuthenticationChallengeReference) (*APIPasskeyOptions, error) {
	var out APIPasskeyOptions
	path := "/auth/api/v1/reauthenticate/passkeys/options"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallReauthenticateWithPassword(ctx context.Context, incoming *http.Request, body APIPasswordReauthenticationRequest) error {
	path := "/auth/api/v1/reauthenticate/password"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallLogout(ctx context.Context, incoming *http.Request) error {
	path := "/auth/api/v1/sessions/logout"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, nil, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallRefreshSession(ctx context.Context, incoming *http.Request, audience string) error {
	path := "/auth/api/v1/sessions/refresh"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, nil, nil, apiRequestOptions(incoming, []string{"authara_csrf", "authara_refresh"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallStartSignupChallenge(ctx context.Context, incoming *http.Request, audience string, body APISignupRequest) (*APISignupChallenge, error) {
	var out APISignupChallenge
	path := "/auth/api/v1/signup/challenges"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallVerifySignupChallenge(ctx context.Context, incoming *http.Request, audience string, body APISignupChallengeVerification) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/signup/challenges/verify"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSignupDirect(ctx context.Context, incoming *http.Request, audience string, body APISignupRequest) (*APIAuthSession, error) {
	var out APIAuthSession
	path := "/auth/api/v1/signup/direct"
	query := url.Values{}
	query.Set("audience", audienceOrApp(audience))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out, apiRequestOptions(incoming, []string{"authara_csrf"}, true)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallRefreshTokens(ctx context.Context, body APITokenRefreshRequest) (*APITokens, error) {
	var out APITokens
	path := "/auth/api/v1/tokens/refresh"
	_, err := c.doJSONBody(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallGetCurrentUser(ctx context.Context, incoming *http.Request) (*APICurrentUser, error) {
	var out APICurrentUser
	path := "/auth/api/v1/user"
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallSetCurrentUserPassword(ctx context.Context, incoming *http.Request, body APISetPasswordRequest) error {
	path := "/auth/api/v1/users/password"
	_, err := c.doJSONBody(ctx, http.MethodPut, path, body, nil, apiRequestOptions(incoming, []string{"authara_access", "authara_csrf"}, true)...)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallListPublicUserMemberships(ctx context.Context, incoming *http.Request, userID uuid.UUID, cursor string, limit int) (*APIUserMemberships, error) {
	var out APIUserMemberships
	path := "/auth/api/v1/users/" + url.PathEscape(userID.String()) + "/memberships"
	query := url.Values{}
	query.Set("cursor", cursor)
	query.Set("limit", strconv.FormatInt(int64(limit), 10))
	path += "?" + query.Encode()
	_, err := c.doJSONBody(ctx, http.MethodGet, path, nil, &out, apiRequestOptions(incoming, []string{"authara_access"}, false)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallCreateInternalOrganization(ctx context.Context, body APIInternalCreateOrganizationRequest) (*APIOrganizationWithMembership, error) {
	var out APIOrganizationWithMembership
	path := "/auth/internal/v1/organizations"
	err := c.internalJSON(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallDeleteInternalOrganization(ctx context.Context, organizationID uuid.UUID, body APIInternalOrganizationActorRequest) error {
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + ""
	err := c.internalJSON(ctx, http.MethodDelete, path, body, nil)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallCreateInternalOrganizationInvitation(ctx context.Context, organizationID uuid.UUID, body APIInternalCreateInvitationRequest) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations"
	err := c.internalJSON(ctx, http.MethodPost, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallResendInternalOrganizationInvitation(ctx context.Context, organizationID uuid.UUID, invitationID uuid.UUID) (*APIOrganizationInvitationEnvelope, error) {
	var out APIOrganizationInvitationEnvelope
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/invitations/" + url.PathEscape(invitationID.String()) + "/resend"
	err := c.internalJSON(ctx, http.MethodPost, path, nil, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallUpdateInternalOrganizationMember(ctx context.Context, organizationID uuid.UUID, userID uuid.UUID, body APIInternalUpdateOrganizationMemberRequest) (*APIOrganizationMemberEnvelope, error) {
	var out APIOrganizationMemberEnvelope
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members/" + url.PathEscape(userID.String()) + ""
	err := c.internalJSON(ctx, http.MethodPatch, path, body, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) CallRemoveInternalOrganizationMember(ctx context.Context, organizationID uuid.UUID, userID uuid.UUID, body APIInternalOrganizationActorRequest) error {
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/members/" + url.PathEscape(userID.String()) + ""
	err := c.internalJSON(ctx, http.MethodDelete, path, body, nil)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallTransferInternalOrganizationOwnership(ctx context.Context, organizationID uuid.UUID, body APIInternalOwnershipTransferRequest) error {
	path := "/auth/internal/v1/organizations/" + url.PathEscape(organizationID.String()) + "/ownership-transfer"
	err := c.internalJSON(ctx, http.MethodPost, path, body, nil)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) CallDeleteInternalUser(ctx context.Context, userID uuid.UUID) error {
	path := "/auth/internal/v1/users/" + url.PathEscape(userID.String()) + ""
	err := c.internalJSON(ctx, http.MethodDelete, path, nil, nil)
	if err != nil {
		return err
	}
	return nil
}
