// Code generated by authara-sdk-gen from authara-core/contract/openapi.yaml; DO NOT EDIT.

package authara

import (
	"time"

	"github.com/google/uuid"
)

type APIAPIError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type APIAccount struct {
	AuthMethods        []APIAuthMethod     `json:"auth_methods"`
	Passkeys           []APIAccountPasskey `json:"passkeys"`
	PasskeysNextCursor *string             `json:"passkeys_next_cursor,omitempty"`
	Sessions           []APIAccountSession `json:"sessions"`
	SessionsNextCursor *string             `json:"sessions_next_cursor,omitempty"`
	User               APIAuthUser         `json:"user"`
}

type APIAccountPasskey struct {
	CreatedAt  time.Time  `json:"created_at"`
	ID         uuid.UUID  `json:"id"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	Name       string     `json:"name"`
}

type APIAccountRecoveryAppleProofRequest struct {
	Code            string  `json:"code"`
	InvitationToken *string `json:"invitation_token,omitempty"`
	State           string  `json:"state"`
}

type APIAccountRecoveryGoogleProofRequest struct {
	Credential      string  `json:"credential"`
	InvitationToken *string `json:"invitation_token,omitempty"`
	Nonce           string  `json:"nonce"`
}

type APIAccountRecoveryLink struct {
	LinkID       uuid.UUID `json:"link_id"`
	ProofMethods []string  `json:"proof_methods"`
}

type APIAccountRecoveryPasswordProofRequest struct {
	InvitationToken *string `json:"invitation_token,omitempty"`
	Password        string  `json:"password"`
}

type APIAccountSession struct {
	CreatedAt time.Time `json:"created_at"`
	Current   bool      `json:"current"`
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
	UserAgent string    `json:"user_agent"`
}

type APIAppleAuthorizationRequest struct {
	Code            string  `json:"code"`
	InvitationToken *string `json:"invitation_token,omitempty"`
	State           string  `json:"state"`
}

type APIAppleLoginOptions struct {
	ClientID    string `json:"client_id"`
	Nonce       string `json:"nonce"`
	RedirectUri string `json:"redirect_uri"`
	State       string `json:"state"`
}

type APIAppleReauthenticationRequest struct {
	AuthenticationChallengeID uuid.UUID `json:"authentication_challenge_id"`
	Code                      string    `json:"code"`
	State                     string    `json:"state"`
}

type APIAuthMethod struct {
	CreatedAt time.Time `json:"created_at"`
	Provider  string    `json:"provider"`
}

type APIAuthSession struct {
	AccessToken  string      `json:"access_token"`
	RefreshToken string      `json:"refresh_token"`
	User         APIAuthUser `json:"user"`
}

type APIAuthUser struct {
	CreatedAt       time.Time  `json:"created_at"`
	Disabled        bool       `json:"disabled"`
	Email           string     `json:"email"`
	EmailVerified   bool       `json:"email_verified"`
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`
	ID              uuid.UUID  `json:"id"`
	Username        string     `json:"username"`
}

type APIAuthenticationChallenge struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
}

type APIAuthenticationChallengeReference struct {
	AuthenticationChallengeID uuid.UUID `json:"authentication_challenge_id"`
}

type APICSRFToken struct {
	CSRFToken string `json:"csrf_token"`
}

type APICapabilities struct {
	AllowsInvitations                  bool   `json:"allows_invitations"`
	AllowsOrgSwitching                 bool   `json:"allows_org_switching"`
	AllowsOrganizationLeave            bool   `json:"allows_organization_leave"`
	AllowsPublicOrganizationManagement bool   `json:"allows_public_organization_management"`
	AllowsUserCreatedTeamOrgs          bool   `json:"allows_user_created_team_orgs"`
	HasVisibleOrganizations            bool   `json:"has_visible_organizations"`
	OrganizationMode                   string `json:"organization_mode"`
}

type APIChallengeReference struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
}

type APIChallengeVerification struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
	Code        string    `json:"code"`
}

type APIChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

type APIChangeUsernameRequest struct {
	Username string `json:"username"`
}

type APICurrentOrganizationMember struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     string              `json:"email"`
	Role      APIOrganizationRole `json:"role"`
	UserID    uuid.UUID           `json:"user_id"`
	Username  string              `json:"username"`
}

type APICurrentOrganizationMembers struct {
	Members    []APICurrentOrganizationMember `json:"members"`
	NextCursor *string                        `json:"next_cursor,omitempty"`
}

type APICurrentUser struct {
	CreatedAt       time.Time              `json:"created_at"`
	Disabled        bool                   `json:"disabled"`
	Email           string                 `json:"email"`
	EmailVerified   bool                   `json:"email_verified"`
	EmailVerifiedAt *time.Time             `json:"email_verified_at,omitempty"`
	ID              uuid.UUID              `json:"id"`
	Organization    APIOrganizationSummary `json:"organization"`
	Roles           []string               `json:"roles"`
	Username        string                 `json:"username"`
}

type APIEmailChangeRequest struct {
	NewEmail string `json:"new_email"`
}

type APIErrorResponse struct {
	AuthenticationChallenge *APIAuthenticationChallenge `json:"authentication_challenge,omitempty"`
	Error                   APIAPIError                 `json:"error"`
	ReauthenticateURL       *string                     `json:"reauthenticate_url,omitempty"`
}

type APIGoogleLoginOptions struct {
	ClientID string `json:"client_id"`
	Nonce    string `json:"nonce"`
}

type APIGoogleLoginRequest struct {
	Credential string `json:"credential"`
	Nonce      string `json:"nonce"`
}

type APIGoogleReauthenticationRequest struct {
	AuthenticationChallengeID uuid.UUID `json:"authentication_challenge_id"`
	Credential                string    `json:"credential"`
	Nonce                     string    `json:"nonce"`
}

type APIInternalCreateInvitationRequest struct {
	ActorUserID uuid.UUID                      `json:"actor_user_id"`
	Email       string                         `json:"email"`
	Metadata    *map[string]any                `json:"metadata,omitempty"`
	Role        *APIOrganizationInvitationRole `json:"role,omitempty"`
}

type APIInternalCreateOrganizationRequest struct {
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
	Name            string    `json:"name"`
}

type APIInternalOrganizationActorRequest struct {
	ActorUserID uuid.UUID `json:"actor_user_id"`
}

type APIInternalOwnershipTransferRequest struct {
	ActorUserID    uuid.UUID `json:"actor_user_id"`
	NewOwnerUserID uuid.UUID `json:"new_owner_user_id"`
}

type APIInternalUpdateOrganizationMemberRequest struct {
	ActorUserID uuid.UUID                 `json:"actor_user_id"`
	Role        APIOrganizationMemberRole `json:"role"`
}

type APIInvitationGoogleRequest struct {
	Credential string `json:"credential"`
	Flow       string `json:"flow"`
	Nonce      string `json:"nonce"`
	Token      string `json:"token"`
}

type APIInvitationGoogleResult struct {
	Recovery *APIAccountRecoveryLink `json:"recovery,omitempty"`
	Session  *APIAuthSession         `json:"session,omitempty"`
	Status   string                  `json:"status"`
}

type APIInvitationPasswordLoginRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

type APIInvitationPreview struct {
	Invitation   APIOrganizationInvitation `json:"invitation"`
	Organization APIOrganization           `json:"organization"`
}

type APIInvitationTokenRequest struct {
	Token string `json:"token"`
}

type APIMembership struct {
	CreatedAt      time.Time           `json:"created_at"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	UpdatedAt      time.Time           `json:"updated_at"`
	UserID         uuid.UUID           `json:"user_id"`
}

type APIMembershipWithOrganization struct {
	Membership   APIMembership   `json:"membership"`
	Organization APIOrganization `json:"organization"`
}

type APIOrganization struct {
	CreatedAt       time.Time  `json:"created_at"`
	CreatedByUserID *uuid.UUID `json:"created_by_user_id,omitempty"`
	ID              uuid.UUID  `json:"id"`
	Kind            string     `json:"kind"`
	Name            string     `json:"name"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type APIOrganizationEnvelope struct {
	Organization APIOrganization `json:"organization"`
}

type APIOrganizationInvitation struct {
	Email          string              `json:"email"`
	ExpiresAt      time.Time           `json:"expires_at"`
	ID             uuid.UUID           `json:"id"`
	InviteURL      *string             `json:"invite_url,omitempty"`
	Metadata       map[string]any      `json:"metadata"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	Status         string              `json:"status"`
}

type APIOrganizationInvitationEnvelope struct {
	Invitation APIOrganizationInvitation `json:"invitation"`
}

type APIOrganizationInvitationRole string

type APIOrganizationInvitations struct {
	Invitations []APIOrganizationInvitation `json:"invitations"`
	NextCursor  *string                     `json:"next_cursor,omitempty"`
}

type APIOrganizationMember struct {
	CreatedAt      time.Time           `json:"created_at"`
	Disabled       bool                `json:"disabled"`
	Email          string              `json:"email"`
	OrganizationID uuid.UUID           `json:"organization_id"`
	Role           APIOrganizationRole `json:"role"`
	UpdatedAt      time.Time           `json:"updated_at"`
	UserID         uuid.UUID           `json:"user_id"`
	Username       string              `json:"username"`
}

type APIOrganizationMemberEnvelope struct {
	Member APIOrganizationMember `json:"member"`
}

type APIOrganizationMemberRole string

type APIOrganizationMembers struct {
	Members    []APIOrganizationMember `json:"members"`
	NextCursor *string                 `json:"next_cursor,omitempty"`
}

type APIOrganizationRole string

type APIOrganizationSummaries struct {
	NextCursor    *string                  `json:"next_cursor,omitempty"`
	Organizations []APIOrganizationSummary `json:"organizations"`
}

type APIOrganizationSummary struct {
	ID   uuid.UUID           `json:"id"`
	Name string              `json:"name"`
	Role APIOrganizationRole `json:"role"`
}

type APIOrganizationWithMembership struct {
	Membership   APIMembership   `json:"membership"`
	Organization APIOrganization `json:"organization"`
}

type APIPasskeyAuthenticationFinishRequest struct {
	ChallengeID uuid.UUID      `json:"challenge_id"`
	Credential  map[string]any `json:"credential"`
}

type APIPasskeyOptions struct {
	ChallengeID uuid.UUID      `json:"challenge_id"`
	Options     map[string]any `json:"options"`
}

type APIPasskeyReauthenticationFinishRequest struct {
	AuthenticationChallengeID uuid.UUID      `json:"authentication_challenge_id"`
	ChallengeID               uuid.UUID      `json:"challenge_id"`
	Credential                map[string]any `json:"credential"`
}

type APIPasskeyRegistrationFinishRequest struct {
	ChallengeID  uuid.UUID      `json:"challenge_id"`
	Credential   map[string]any `json:"credential"`
	Name         *string        `json:"name,omitempty"`
	PlatformHint *string        `json:"platform_hint,omitempty"`
}

type APIPasswordLoginRequest struct {
	Identifier string `json:"identifier"`
	Password   string `json:"password"`
}

type APIPasswordReauthenticationRequest struct {
	AuthenticationChallengeID uuid.UUID `json:"authentication_challenge_id"`
	Password                  string    `json:"password"`
}

type APIPasswordResetChallengeVerification struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
	Code        string    `json:"code"`
}

type APIPasswordResetRequest struct {
	Email       string `json:"email"`
	NewPassword string `json:"new_password"`
}

type APIRevokeInvitationRequest struct {
	RevokedByUserID *uuid.UUID `json:"revoked_by_user_id,omitempty"`
}

type APISetPasswordRequest struct {
	Password string `json:"password"`
}

type APISignupChallenge struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
}

type APISignupChallengeVerification struct {
	ChallengeID uuid.UUID `json:"challenge_id"`
	Code        string    `json:"code"`
}

type APISignupRequest struct {
	Email          string  `json:"email"`
	InvitationCode *string `json:"invitation_code,omitempty"`
	Password       string  `json:"password"`
}

type APITokenRefreshRequest struct {
	Audience     *string `json:"audience,omitempty"`
	RefreshToken string  `json:"refresh_token"`
}

type APITokens struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type APIUpdateOrganizationMemberRequest struct {
	Role APIOrganizationMemberRole `json:"role"`
}

type APIUpdateOrganizationRequest struct {
	Name string `json:"name"`
}

type APIUserMemberships struct {
	Memberships []APIMembershipWithOrganization `json:"memberships"`
	NextCursor  *string                         `json:"next_cursor,omitempty"`
}

const APIAcceptInvitationAudienceApp = "app"

const APIAccountRecoveryLinkProofMethodsItemApple = "apple"

const APIAccountRecoveryLinkProofMethodsItemGoogle = "google"

const APIAccountRecoveryLinkProofMethodsItemPassword = "password"

const APIAppAudienceApp = "app"

const APIAudienceAdmin = "admin"

const APIAudienceApp = "app"

const APIAudienceOperator = "operator"

const APIAuthMethodProviderApple = "apple"

const APIAuthMethodProviderGoogle = "google"

const APIAuthMethodProviderPassword = "password"

const APIAuthProviderApple = "apple"

const APIAuthProviderGoogle = "google"

const APIAuthProviderPassword = "password"

const APIAuthenticateAndAcceptInvitationWithGoogleAudienceApp = "app"

const APICapabilitiesOrganizationModeMulti = "multi"

const APICapabilitiesOrganizationModePersonal = "personal"

const APICapabilitiesOrganizationModeSingle = "single"

const APICompleteAccountRecoveryLinkWithAppleAudienceApp = "app"

const APICompleteAccountRecoveryLinkWithGoogleAudienceApp = "app"

const APICompleteAccountRecoveryLinkWithPasswordAudienceApp = "app"

const APICurrentUserRolesItemAutharaAdmin = "authara:admin"

const APICurrentUserRolesItemAutharaOperator = "authara:operator"

const APIFinishPasskeyAuthenticationAudienceAdmin = "admin"

const APIFinishPasskeyAuthenticationAudienceApp = "app"

const APIFinishPasskeyAuthenticationAudienceOperator = "operator"

const APIInvitationGoogleRequestFlowLogin = "login"

const APIInvitationGoogleRequestFlowSignup = "signup"

const APIInvitationGoogleResultStatusAuthenticated = "authenticated"

const APIInvitationGoogleResultStatusProofRequired = "proof_required"

const APILoginAndAcceptInvitationAudienceApp = "app"

const APILoginWithAppleAudienceAdmin = "admin"

const APILoginWithAppleAudienceApp = "app"

const APILoginWithAppleAudienceOperator = "operator"

const APILoginWithGoogleAudienceAdmin = "admin"

const APILoginWithGoogleAudienceApp = "app"

const APILoginWithGoogleAudienceOperator = "operator"

const APILoginWithPasswordAudienceAdmin = "admin"

const APILoginWithPasswordAudienceApp = "app"

const APILoginWithPasswordAudienceOperator = "operator"

const APIOrganizationInvitationRoleAdmin APIOrganizationInvitationRole = "admin"

const APIOrganizationInvitationRoleMember APIOrganizationInvitationRole = "member"

const APIOrganizationInvitationStatusAccepted = "accepted"

const APIOrganizationInvitationStatusExpired = "expired"

const APIOrganizationInvitationStatusPending = "pending"

const APIOrganizationInvitationStatusRevoked = "revoked"

const APIOrganizationKindPersonal = "personal"

const APIOrganizationKindTeam = "team"

const APIOrganizationMemberRoleAdmin APIOrganizationMemberRole = "admin"

const APIOrganizationMemberRoleMember APIOrganizationMemberRole = "member"

const APIOrganizationRoleAdmin APIOrganizationRole = "admin"

const APIOrganizationRoleMember APIOrganizationRole = "member"

const APIOrganizationRoleOwner APIOrganizationRole = "owner"

const APIRefreshSessionAudienceAdmin = "admin"

const APIRefreshSessionAudienceApp = "app"

const APIRefreshSessionAudienceOperator = "operator"

const APISignupDirectAudienceApp = "app"

const APIStartSignupChallengeAudienceApp = "app"

const APISwitchOrganizationAudienceAdmin = "admin"

const APISwitchOrganizationAudienceApp = "app"

const APISwitchOrganizationAudienceOperator = "operator"

const APITokenRefreshRequestAudienceAdmin = "admin"

const APITokenRefreshRequestAudienceApp = "app"

const APITokenRefreshRequestAudienceOperator = "operator"

const APIVerifySignupChallengeAudienceApp = "app"
